# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

jobs:
  abaplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Run npm steps
      run: |
        npm install
        npm run merge
        npm run merge.ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        

      # Runs a single command using the runners shell
    
