# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

jobs:
  abaplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: abaplint
      uses: abaplint/actions-abaplint@main
    - name: merge
      
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        

      # Runs a single command using the runners shell
    
