# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

jobs:
  abaplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Run npm steps
      run: |
        npm install
        npm run merge
        npm run merge.ci
    - name: deploy-merged-build
      if: github.ref == 'refs/heads/main' && github.repository == 'reyemsaibot/scf'
      env:
        GITHUB_API_KEY: ${{ secrets.MY_SECRET }}
      run: | 
       chmod +x ./ci/deploy-merged-build.sh
       ./ci/deploy-merged-build.sh
        

      # Runs a single command using the runners shell
    
